<?php
// module/Album/view/album/album/add.phtml:

$title = 'Додати альбом';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
    <div class="col-xs-12  col-md-10 col-md-offset-1 col-lg-10 col-lg-offset-1 col-sm-10 col-sm-1">
        <?php
        $form = $this->form;
        $form->setAttribute('action', $this->url('album', array('action' => 'add')));
        ?>
        <?php
        $form->prepare();

        echo $this->form()->openTag($form);
        echo $this->formCollection($form);
        ?>
    </div>

        <?php
        echo $this->form()->closeTag();
